# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /


spring:
  # ?? dev|test|prod
  profiles:
    active: dev